// lib/profileName.ts
import AsyncStorage from "@react-native-async-storage/async-storage";
import { generateDeterministicName } from "./randomName";

const KEY = "display_name_v1";

export async function getDisplayName() {
  const stored = await AsyncStorage.getItem(KEY);
  if (stored) return stored;

  const generated = await generateDeterministicName();
  // do NOT store the generated by default — keeps it auto-updating if we later
  // improve the generator; store only when the user explicitly edits the name.
  return generated;
}

export async function setDisplayName(name: string) {
  await AsyncStorage.setItem(KEY, name);
}