/**
 * scripts/generateCountryQuestions.ts
 *
 * Works with Natural Earth 110m files that only have:
 *   { id: ISO3, properties: { name }, geometry: ... }
 * and NO continent fields.
 *
 * Output -> app/data/questions.countries.json
 */

import fs from "node:fs";
import path from "node:path";

// Load region mapping (ISO-3 and/or ISO-2) from app/data/regions.json
const REGIONS_PATH = path.resolve("app/data/regions.json");
let REGIONS: Record<string, string> = {};
try {
  if (fs.existsSync(REGIONS_PATH)) {
    REGIONS = JSON.parse(fs.readFileSync(REGIONS_PATH, "utf8")) as Record<string, string>;
  }
} catch {
  // ignore, we'll default to "Other" when missing
}

function regionFor(opts: { iso3?: string; iso2?: string; fallback?: string }) {
  const iso3 = opts.iso3?.toUpperCase();
  const iso2 = opts.iso2?.toUpperCase();
  if (iso3 && REGIONS[iso3]) return REGIONS[iso3];
  if (iso2 && REGIONS[iso2]) return REGIONS[iso2];
  return opts.fallback ?? "Other";
}

// Read the set of ISO2 codes that we actually have flag assets for
// (generated by scripts/extractIso2FromFlags.ts -> app/data/availableIso2.json).
function readAvailableIso2(): Set<string> {
  const p = path.resolve("app/data/availableIso2.json");
  if (!fs.existsSync(p)) return new Set();
  try {
    const arr = JSON.parse(fs.readFileSync(p, "utf8")) as string[];
    return new Set(arr.map(s => s.toLowerCase()));
  } catch {
    return new Set();
  }
}

const OUT_FILE = path.resolve("app/data/questions.countries.json");
const INPUT_CANDIDATES = [
  path.resolve("assets/countries-110m.json"),
  path.resolve("assets/countries-110m.geojson"),
  path.resolve("app/assets/countries-110m.json"),
];

// Your current easy/hard sets
const EASY = new Set<string>([
  "United States of America","United Kingdom","France","Germany","Italy","Spain","Portugal",
  "Netherlands","Belgium","Switzerland","Austria","Sweden","Norway","Denmark","Finland",
  "Poland","Czechia","Ireland","Greece","Turkey","Russia","Canada","Mexico","Brazil",
  "Argentina","Chile","Colombia","Peru","Australia","New Zealand","Japan","South Korea",
  "China","India","Pakistan","Bangladesh","Indonesia","Philippines","Thailand","Vietnam",
  "Saudi Arabia","United Arab Emirates","South Africa","Egypt","Nigeria","Kenya","Morocco",
]);
const HARD = new Set<string>([
  "Andorra","Monaco","San Marino","Liechtenstein","Vatican","Luxembourg","Iceland","Malta",
  "Eswatini","Lesotho","Djibouti","Eritrea","Gabon","Equatorial Guinea","Sao Tome and Principe",
  "Comoros","Seychelles","Mauritius","Cabo Verde","Timor-Leste","Brunei","Bhutan","Laos",
  "Suriname","Guyana","Belize","Antigua and Barbuda","Saint Kitts and Nevis","Dominica",
  "Saint Lucia","Saint Vincent and the Grenadines","Barbados","Grenada","Trinidad and Tobago",
  "Solomon Islands","Vanuatu","Kiribati","Tonga","Samoa","Fiji","Marshall Islands","Micronesia",
  "Palau","Nauru","Tuvalu","Bahrain","Qatar","Kuwait","Moldova","North Macedonia","Kosovo",
  "Bosnia and Herzegovina","Montenegro","Albania","Armenia","Azerbaijan","Georgia",
]);

// Minimal ISO3->ISO2 map so flags work for the most common countries.
// (We can expand this later; if undefined, the UI can just omit the flag.)
const ISO3_TO_ISO2: Record<string, string> = {
  USA: "us", GBR: "gb", FRA: "fr", DEU: "de", ITA: "it", ESP: "es", PRT: "pt",
  NLD: "nl", BEL: "be", CHE: "ch", AUT: "at", SWE: "se", NOR: "no", DNK: "dk", FIN: "fi",
  POL: "pl", CZE: "cz", IRL: "ie", GRC: "gr", TUR: "tr", RUS: "ru", CAN: "ca", MEX: "mx", BRA: "br",
  ARG: "ar", CHL: "cl", COL: "co", PER: "pe", AUS: "au", NZL: "nz", JPN: "jp", KOR: "kr",
  CHN: "cn", IND: "in", PAK: "pk", BGD: "bd", IDN: "id", PHL: "ph", THA: "th", VNM: "vn",
  SAU: "sa", ARE: "ae", ZAF: "za", EGY: "eg", NGA: "ng", KEN: "ke", MAR: "ma",
};

function difficultyForCountry(name: string): "easy" | "medium" | "hard" {
  if (EASY.has(name)) return "easy";
  if (HARD.has(name)) return "hard";
  return "medium";
}

function firstExisting(paths: string[]): string | null {
  for (const p of paths) if (fs.existsSync(p)) return p;
  return null;
}

function main() {
  const input = firstExisting(INPUT_CANDIDATES);
  if (!input) {
    console.error("No countries input found at:", INPUT_CANDIDATES.join(", "));
    process.exit(1);
  }
  const availableIso2 = readAvailableIso2();

  const raw = JSON.parse(fs.readFileSync(input, "utf8"));
  const feats: any[] = raw.features || [];

  const out: any[] = [];

  for (const f of feats) {
    const iso3: string | undefined = f.id || f.properties?.ISO_A3 || f.properties?.ADM0_A3;
    const name: string | undefined = f.properties?.name || f.properties?.NAME || f.properties?.ADMIN;
    if (!iso3 || !name) continue;
    if (iso3 === "ATA" || name === "Antarctica") continue; // skip Antarctica

    const mappedIso2 = ISO3_TO_ISO2[iso3];
    const iso2 = mappedIso2 ? mappedIso2.toLowerCase() : undefined;
    const hasFlag = iso2 ? availableIso2.has(iso2) : false;
    const region = regionFor({ iso3, iso2 });

    out.push({
      id: `country:${iso3.toLowerCase()}`,
      type: "country",
      answer: name,
      iso3,
      ...(hasFlag && iso2 ? { iso2 } : {}),
      difficulty: difficultyForCountry(name),
      region,
    });
  }

  out.sort((a, b) => a.answer.localeCompare(b.answer));
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, JSON.stringify(out, null, 2));
  console.log(`Wrote ${out.length} country questions -> ${OUT_FILE}`);
}

main();