// scripts/genFlagsMap.mjs
// -----------------------------------------------------------------------------
// PURPOSE: Generate a static TypeScript map of ISO2 -> require(path/to/flag.png)
// OUTPUT : lib/flags.ts
//
// NOTES
// - This script is pure Node (ESM) and **does not** reference app runtime code.
// - It scans `assets/flags/*.png` and writes a single source of truth used by
//   the app at runtime. Keep all app-side flag lookups importing from `lib/flags`.
// -----------------------------------------------------------------------------

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = process.cwd();

// From lib/  -> assets/  we need one ".."
const FLAGS_DIR = path.resolve(ROOT, "assets/flags");
const OUT_FILE  = path.resolve(ROOT, "lib/flags.ts");

function isPng(name) {
  return /\.png$/i.test(name);
}

function iso2FromFilename(name) {
  // Accept ad.png, AD.png, ad@2x.png (strip scale suffix), etc.
  const base = name.replace(/@[\dx]+(?=\.)/i, ""); // remove @2x-like
  return path.basename(base, path.extname(base)).toLowerCase(); // "ad"
}

function main() {
  if (!fs.existsSync(FLAGS_DIR)) {
    console.error(`Flags directory not found: ${FLAGS_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(FLAGS_DIR).filter(isPng);

  // Build map code lines
  const entries = [];
  for (const file of files) {
    const code = iso2FromFilename(file);
    if (!/^[a-z]{2}$/.test(code)) {
      // Skip non-ISO2 entries silently
      continue;
    }
    // Path from lib -> assets
    const relRequire = `../assets/flags/${file}`;
    entries.push(`  '${code}': require('${relRequire}') as ImageSourcePropType,`);
  }

  entries.sort((a, b) => {
    // sort by key ('  'xx'': ...) for stable output
    const ak = a.slice(2, 4);
    const bk = b.slice(2, 4);
    return ak.localeCompare(bk);
  });

  const outSource = `// AUTO-GENERATED BY scripts/genFlagsMap.mjs — DO NOT EDIT BY HAND.
import type { ImageSourcePropType } from "react-native";

export const FLAG_MAP: Record<string, ImageSourcePropType> = {
${entries.join("\n")}
};

export function getFlagSource(iso2: string): ImageSourcePropType | undefined {
  const k = (iso2 || "").toLowerCase();
  return FLAG_MAP[k];
}
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, outSource, "utf8");
  console.log(`Wrote ${OUT_FILE} with ${entries.length} flags.`);
}

main();